### ISSUE TITLE
CU18 has disppeared, CU19 details are here.

### ISSUE THREAD

**Issue by westy** [tfenster/mssql-image#12]
Link: https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5023049-x64.exe

Version: 15.0.4298.1

Cheers

**Comment by tfenster** [comment]
@westy Thanks for letting me know! I've updated the required files and created a new tag. Also my own builds are running, so I'll know whether it works or not although I can't make the images available anymore
