### ISSUE TITLE
CU19 has gone, CU20 details here!

### ISSUE THREAD

**Issue by westy** [tfenster/mssql-image#13]
Linky: https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5024276-x64.exe

Version: 15.0.4312.2

Cheers!

**Comment by tfenster** [comment]
@westy Fixed with https://github.com/tfenster/mssql-image/commit/8b55cc9c95ad19b7717bc6ae0bb8d2b2b5bb8953, thanks!
