### ISSUE TITLE
Issue with building due to choco change?

### ISSUE THREAD

**Issue by westy** [tfenster/mssql-image#14]
Hi mate,

Me again!

Looks like need a tweak to get the build working, since was getting an error when calling refreshenv.
The error hinted at the solution.

The change that worked for me is this:
```
RUN $ProgressPreference = 'SilentlyContinue'; `
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); `
    choco feature enable -n allowGlobalConfirmation; `
    choco install --no-progress --limit-output vim 7zip sqlpackage; `
    Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1; `
    refreshenv;
```
I added the `Import-Module` call.

Oh, looks like CU20 may have gone missing too, since it failed later whilst I was writing this.

CU21 is here: https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5025808-x64.exe

Cheers,
Westy

**Comment by westy** [comment]
Version is 15.0.4316.3

**Comment by tfenster** [comment]
@westy I've made the changes and kicked of the action, hopefully it'll work. Btw, I am happy to just use your input, but if you want, feel also free to just create a Pull Request. I'd review of course :)
