### ISSUE TITLE
Building Docker File

### ISSUE THREAD

**Issue by mazharcts** [tfenster/mssql-image#15]
Hi,

Iam new to Docker and stuff , working to containerize an web app (.Net Framework) dealing with Windows container.

Can you please let me know how do i build this and link it with the container which has the App running inside it? or connect to SQL from the container ?

Came through you blog : https://tobiasfenster.io/ms-sql-server-in-windows-containers
And what is it with CU 20 and CU 19 ?

Iam sorry if am asking anything silly any help will be grateful.

Thanks

**Comment by tfenster** [comment]
Hi @mazharcts, you need to run a `docker build` as you can see at the bottom of the blog post that you mentioned. This would give you an image, which you can use to create a container with a `docker run` as seen in the TL;DR section of the blog post. Then you can connect with your .NET web app to it. And I am not sure what you mean with "And what is it with CU 20 and CU 19 ?"?
