### ISSUE TITLE
Find older SQL Builds

### ISSUE THREAD

**Issue by CptBlaubart** [tfenster/mssql-image#6]
I need dynamic access for different builds of SQL for an Upgrade automation for BC (business central) I'm working on. - Reason beeing: Some customers want to upgrade to BC onPrem but want to keept their SQL Licese as it is still supported by BC, but once you opened a Database on a newer release, i've been told you're not able to restore that database on an older one.

if i try to find sources for older images, https://github.com/microsoft/mssql-docker redirects me to this page here: https://hub.docker.com/u/microsoft where i can't find any sql server images. Can you help me out here? I'm not really that deep into docker to build my own images, and I'm also hesitating to use any of the 3rd party images on docker hub. - Who knows whats going on in those?!

**Comment by tfenster** [comment]
There are no officially supported images as announced here https://techcommunity.microsoft.com/t5/sql-server-blog/update-beta-program-for-sql-server-on-windows-container-is/bc-p/2564521 and explained a bit more here https://tobiasfenster.io/ms-sql-server-in-windows-containers. So if you want to use SQL Server in Windows containers, your only options are building your own images or using 3rd party images like those generated from this repo

**Comment by CptBlaubart** [comment]
ok
