### ISSUE TITLE
2019 latest CU tag

### ISSUE THREAD

**Issue by DatKyle** [tfenster/mssql-image#9]
Would it be possible to have a docker tag called `2019` or `2019-latest` which contains the latest CU?

**Comment by tfenster** [comment]
@DatKyle sure, we could do that. Something seems to have gone wrong with the latest builds as the actions look good but only a few images made into the Docker hub. I will have to investigate but have trouble to find the time right now. I hope to be able to work on it next week and also include your proposal

**Comment by DatKyle** [comment]
No worries, if you need a hand just let me know, not familiar with Github actions but always happy to help.

**Comment by tfenster** [comment]
Thanks for the offer. I think the first step is to go through the build logs e.g. here https://github.com/tfenster/mssql-image/runs/5020536834?check_suite_focus=true to find out why they fail and then why the build still succeeds... If you have the time, I would be very interested in what you find

**Comment by DatKyle** [comment]
@tfenster, I've had a look through the logs and the following tags don't exist:
- `mssql-server-dev-unsupported:15.0.4198.2-2004`
  - `mssql-server-dev-unsupported:2019-cu15-2004`
- `mssql-server-dev-unsupported:15.0.4198.2-20H2`
  - `mssql-server-dev-unsupported:2019-cu15-20H2`
- `mssql-server-dev-unsupported:15.0.4198.2-ltsc2022`
  - `mssql-server-dev-unsupported:2019-cu15-ltsc2022`

The Push Docker Image returns the below message:
```
docker push ***/mssql-server-dev-unsupported:2019-cu15-ltsc2022
The push refers to repository [docker.io/***/mssql-server-dev-unsupported]
tag does not exist: ***/mssql-server-dev-unsupported:2019-cu15-ltsc2022
```
The 3 builds failed at Step 15/18: 
```
Install CU from http://download.windowsupdate.com/d/msdownload/update/software/updt/2022/01/sqlserver2019-kb5008996-x64_f914e20d97650c2b2c09bd8f3d35d3f0feb1afd3.exe
```
I've attached the logs, But it looks like the step reported the patching was finished but it was still preparing files...
[5_Build Docker images.txt](https://github.com/tfenster/mssql-image/files/8010811/5_Build.Docker.images.txt)


### Unrelated but I'm a little confused by it...
Looking at the Manifest Create and Push, it's also creating/pushing manifests for images that don't exist, as part of this build action:
```
Created manifest list docker.io/***/mssql-server-exp-unsupported:2019-cu15
```
The Docker Build command builds 2 tags, a CU and Version tag:
- ***/mssql-server-dev-unsupported:15.0.4198.2-20H2
- ***/mssql-server-dev-unsupported:2019-cu15-20H2
The Docker Push only pushes those tags, so I'm unsure why it is doing stuff to the `2019-cu15` tag...

**Comment by tfenster** [comment]
@DatKyle sorry for the delay. I made a couple of attempts, but didn't get far :( I hope to find more time on one of the next weekends

**Comment by DatKyle** [comment]
No worries, If you need any help with it, I'm more than happy to help where possible 🙂

**Comment by tfenster** [comment]
My big question is why the build fails, although we have

```
2022-02-01T12:55:58.3192463Z Patch done, found expected version 15.0.4198.2
2022-02-01T12:55:58.3258981Z Successfully patched!
```

in the log file you shared. So it shouldn't fail... And if it fails, why doesn't the whole run fail?

For the manifest question: My logic was that I expected the whole run to fail if one of the builds fails. Then the manifest push would never happen. And if all builds succeed, then it is fine to push all tags through the manifest, so I created the manifest push in a way so that it always references all tags, because I expected that all are available if the run makes it to the manifest push part

**Comment by tfenster** [comment]
@DatKyle with the latest Windows Server 2022 release, I could now create a container-based host for the github runs. Let's see if that makes a difference (https://github.com/tfenster/mssql-image/runs/6119567815?check_suite_focus=true)

**Comment by tfenster** [comment]
@DatKyle with the new build host, the builds are working flawlessly again, and I have re-created all images. I have also added a 2019-latest image (https://hub.docker.com/layers/mssql-server-dev-unsupported/tobiasfenster/mssql-server-dev-unsupported/2019-latest/images/sha256-9fbaa1f9ab757625c1cac94c3e71c6e35a1506dc4eff66d42e76c0d52e8eda70?context=explore) for both dev and express. Does that work for you?

**Comment by tfenster** [comment]
closing because of missing feedback
